DROP DATABASE IF EXISTS jhonr1_rugby;
CREATE DATABASE jhonr1_rugby;
USE jhonr1_rugby;
CREATE TABLE persons(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(25) NOT NULL,
last_name VARCHAR(25) NOT NULL,
gender VARCHAR(10) NOT NULL,
dob DATE NOT NULL,
email VARCHAR(100),
photo BLOB
)ENGINE=INNODB;

CREATE TABLE guardians(
caregiver_id BIGINT,
dependant_id BIGINT,
FOREIGN KEY (caregiver_id) REFERENCES persons(id) ON DELETE RESTRICT,
FOREIGN KEY (dependant_id) REFERENCES persons(id) ON DELETE RESTRICT
)ENGINE=INNODB;

CREATE TABLE addresses(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
door_number INT NOT NULL,
street_name VARCHAR(40) NOT NULL,
suburb VARCHAR(30) NOT NULL,
city VARCHAR(30) NOT NULL,
postal_code INT NOT NULL
)ENGINE=INNODB;

CREATE TABLE person_address(
person_id BIGINT NOT NULL,
address_id BIGINT NOT NULL,
FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE RESTRICT,
FOREIGN KEY (address_id) REFERENCES addresses(id) ON DELETE RESTRICT
)ENGINE=INNODB;

CREATE TABLE telephones(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
phone_number VARCHAR(20) NOT NULL,
phone_type VARCHAR(20)
)ENGINE=INNODB;

CREATE TABLE person_telephone(
person_id BIGINT NOT NULL,
telephone_id BIGINT NOT NULL,
FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE RESTRICT,
FOREIGN KEY (telephone_id) REFERENCES telephones(id) ON DELETE RESTRICT
)ENGINE=INNODB;

CREATE TABLE schools(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
address VARCHAR(100) NOT NULL,
telephone VARCHAR(25) NOT NULL
)ENGINE=INNODB;

CREATE TABLE enrollments(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
school_id INT NOT NULL,
person_id BIGINT NOT NULL,
student_year TINYINT,
start_date DATE NOT NULL,
end_date DATE,
FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE RESTRICT,
FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT
)ENGINE=INNODB;

CREATE TABLE coaches(
id INT AUTO_INCREMENT PRIMARY KEY,
person_id BIGINT NOT NULL,
start_date DATE NOT NULL,
end_date DATE,
FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE RESTRICT
)ENGINE=INNODB;

CREATE TABLE qualifications(
id TINYINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL
)ENGINE=INNODB;

CREATE TABLE coach_qualification(
qualification_id TINYINT NOT NULL,
coach_id INT NOT NULL,
FOREIGN KEY (qualification_id) REFERENCES qualifications(id) ON DELETE RESTRICT,
FOREIGN KEY (coach_id) REFERENCES coaches(id) ON DELETE RESTRICT
)ENGINE=INNODB;

CREATE TABLE teams(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(25) NOT NULL,
age TINYINT NOT NULL,
team_year YEAR NOT NULL,
coach_id INT NOT NULL,
FOREIGN KEY (coach_id) REFERENCES coaches(id) ON DELETE RESTRICT
)ENGINE=INNODB;

CREATE TABLE players(
enrollment_id BIGINT NOT NULL,
team_id INT NOT NULL,
FOREIGN KEY (enrollment_id) REFERENCES enrollments(id) ON DELETE RESTRICT,
FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE RESTRICT
)ENGINE=INNODB;



